# adjust base image to whatever version you want to build with
FROM fedora:latest

RUN dnf install -y nasm make gcc gcc-c++ rsync patch glibc zlib-devel gd-devel unzip perl which bzip2 && \
	dnf clean all && \
	rm -rf /var/cache/yum

RUN mkdir /cpan
WORKDIR /cpan

CMD ["/bin/bash"]