# adjust base image to whatever version you want to build with
FROM opensuse/tumbleweed:latest

RUN zypper install -y nasm make gcc gcc-c++ rsync patch glibc zlib-devel gd-devel unzip perl which bzip2 wget tar gzip awk

RUN mkdir /cpan
WORKDIR /cpan

CMD ["/bin/bash"]