name: Build Perl CPAN modules for Lyrion Music Server
on:
  workflow_dispatch:
    inputs:
      flavour:
        description: The Linux flavour we're building for.
        type: choice
        options:
          - debian
          - fedora
          - raspbian
          - suse
        required: true
        default: debian
      tag:
        description: The Docker tag to use to build. Defaults to "testing" for Debian, "latest" for Fedora if left blank.
        type: string
        required: false
      platform:
        description: The hardware platform for which to build.
        type: choice
        options:
          - amd64
          - arm/v6
          - arm64
          - arm/v7
        required: true
        default: amd64
      module:
        description: A specific module you'd like to build. Defaults to all modules if none is specified.
        type: string
        required: false

jobs:
  buildCPAN:
    name: Build Perl CPAN modules
    runs-on: ${{ inputs.platform == 'amd64' && 'ubuntu-latest' || 'ubuntu-24.04-arm' }}

    steps:
      - uses: actions/checkout@v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set requested Docker image tag
        if: ${{ inputs.tag }}
        shell: bash
        run: |
          DOCKERFILE="CPAN/Docker/Dockerfile.${{ inputs.flavour }}"
          sed -Ei 's/:(latest|testing)/:${{ inputs.tag }}/g' $DOCKERFILE

      - name: Run Build Script
        shell: bash
        run: |
          cd CPAN
          docker build --rm --platform=linux/${{ inputs.platform }} -f "Docker/Dockerfile.${{ inputs.flavour }}" -t slimservervendor:${{ inputs.flavour }} .
          docker run --rm --platform=linux/${{ inputs.platform }} -v `pwd`:/cpan slimservervendor:${{ inputs.flavour }} ./buildme.sh ${{ inputs.module }}

      # TODO - run LMS smoke test

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        if: ${{ !env.ACT }}
        with:
          name: CPAN-${{ inputs.flavour }}${{ inputs.tag && format('-{0}', inputs.tag) || ''}}-${{ inputs.platform == 'arm/v6' && 'armv6' || inputs.platform == 'arm/v7' && 'armv7' || inputs.platform }}
          path: CPAN/build/arch/5.*
